---
type: single # single|window, maybe add opt
key: iirnn #added to the csv names
evaluation: evaluation_user_based #evaluation|evaluation_last|evaluation_multiple
data:
  name: delicious #added in the end of the csv names
  folder: data/delicious/prepared/
  prefix: user_taggedbookmarks-timestamps
  type: hdf #hdf (if there is no type, the default is csv)

results:
  folder: results/opt/single/delicious/iirnn/

metrics:
- class: accuracy_multiple.Recall
  length: [5, 20]
- class: accuracy.MRR
  length: [5, 20]

optimize:
  class: accuracy.MRR
  length: [20]
  iterations: 100 #optional

algorithms:
- class: IIRNN.ii_rnn.IIRNN
  params: {max_epoch: 100}
  params_opt:
    dropout_pkeep: {from: 0.1, to: 1.0, in: 10, type: float}
    learning_rate: [{from: 0.01, to: 0.001, in: 10, type: float},{from: 0.001, to: 0.0001, in: 10, type: float}]
    max_session_representation: [1, 5, 10, 15, 20]
    use_last_hidden_state: [True, False]
    embedding_size: [50, 100]
  key: ii_rnn
